@startuml Generate municipality overview

actor Advisor
hide unlinked
participant "cmd" as cmd
participant "Customer repository" as CustomerRepository

activate Advisor
activate cmd
activate CustomerRepository
activate Customer
activate DeviceManager
activate Device
activate surplus

Advisor -> cmd : GenerateOverview("YearAndPrediction")
cmd -> CustomerRepository : customers = findAllCustomers()
loop foreach customer in customers
    cmd -> Customer : getPrices()
    cmd -> Customer : getDeviceManager()
    cmd -> DeviceManager : getDevices()
    loop foreach device in devices
        cmd -> Device : surpluses = getDeviceSurpluses()
    end loop
    loop foreach surplus in surpluses
        cmd -> surplus : amount = getAmount()
        cmd -> surplus : period = getPeriod()
        cmd -> cmd : totalRevenue+=amount * prices[period.getId()]
    end loop
end loop
cmd -> cmd : GenerateSpreadsheet()
cmd --> Advisor : spreadsheet
deactivate Advisor
deactivate cmd
deactivate CustomerRepository
deactivate Customer
deactivate DeviceManager
deactivate Device
deactivate surplus

@enduml